# up to "docker compose -f adminer.yml up -d "
version: "3.1"
services:
  adminer-rb:
    image: adminer
    container_name: adminer-rb
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      - ./.env
#     networks:
#       - caddy
# networks:
#   caddy:
#     external: true
# Use only if you need to reassign the network
