version: "3.9"

services:
  rb-global-api:
    container_name: rb-global-api
    working_dir: /usr/src/app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000" # "Host port(edit for port conflict):container port"
  postgres-rb:
    image: postgres:14
    restart: unless-stopped
    container_name: postgres-rb
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_DB: ${NAME_DB}
      POSTGRES_PASSWORD: ${PASS_DB}
    ports:
      - "5432:5432" # "Host port(edit for port conflict):container port"
