version: "3.9"

services:
  rb-global-api:
    container_name: rb-global-api
    working_dir: /usr/src/app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: npm run start
    ports:
      - "3000:${PORT}"
    env_file:
     - ./.env
    # "Host port(edit for port conflict):container port"
    # networks:
    #   - caddy
  mysql-rb:
    image: mysql:8.0.34
    restart: unless-stopped
    container_name: mysql-rb
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_MYSQL}
      MYSQL_DATABASE: ${NAME_DB}
      MYSQL_USER: ${USER_DB}
      MYSQL_PASSWORD: ${PASS_DB}
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
     - ./.env
    # "Host port(edit for port conflict):container port"
    # networks:
    #   - caddy
# networks:
#   caddy:
#     external: true
# Use only if you need to reassign the network
