# up to "docker compose -f adminer.yml up -d "
version: "3.1"
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8075:80
    env_file:
      - ./.env
    environment:
      PMA_ABSOLUTE_URI: https://pma-rb.zaitsv.dev
    volumes:
      - pma-data:/var/lib/phpmyadmin/data
#     networks:
#       - caddy
# networks:
#   caddy:
#     external: true
# Use only if you need to reassign the network
