# up to "docker compose -f adminer.yml up -d "
version: "3.1"
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8075:80
    env_file:
      - ../.env
#     networks:
#       - caddy
# networks:
#   caddy:
#     external: true
# Use only if you need to reassign the network
